### ISSUE TITLE
agregar encuesta floating action button

### ISSUE THREAD

**Issue by jperelli** [cualbondi/web-buscador#14]

**Comment by marcosfede** [comment]
Esto podria ir en el menu lateral

**Comment by marcosfede** [comment]
podria ser un toast que diga bienvenido a la nueva ui... deja tu sug en el menu lateral

**Comment by marcosfede** [comment]
agregar un rate y un select con opciones de que no te gusta

**Comment by jperelli** [comment]
lo paso para el siguiente sprint, por ahora ya puse una encuesta mas sencilla

**Comment by marcosfede** [comment]
done
