### ISSUE TITLE
zoom muy lejos al elegit "tu ubicacion"

### ISSUE THREAD

**Issue by jperelli** [cualbondi/web-buscador#78]
Steps to reproduce:
1. click en origen
2. elegir en el mapa
3. ok
4. click en destino
5. tu ubiaccion

resultado: el mapa queda muy alejado.

Nota 1: si se vuelve a elegir tu ubicacion, no pasa
Nota 2: si se hace zoom en el mapa y se vuelve a repetir pasos 4 y 5 sucede de nuevo

![whatsapp image 2018-06-27 at 09 21 30](https://user-images.githubusercontent.com/1418446/42004015-673c38bc-7a44-11e8-995b-d8d3c80d3860.jpeg)

**Comment by marcosfede** [comment]
esto parece estar arreglado
